/**
 * The puzzle archive, loaded once and served from memory.
 *
 * `data/puzzles.json` is generated by `tools/build-puzzles.ts`; this module is
 * the only thing that reads it, and it validates on load so a bad build fails
 * at startup instead of halfway through someone's run.
 */

import { readFileSync } from "node:fs";
import {
  byTier,
  DAILY_TIERS,
  type DailyTier,
  type DayOptions,
  dayNumber,
  nextResetAt,
  puzzleIndexForDay,
} from "../shared/daily";
import { BOARD_WIDTH, type Puzzle, type PuzzlePrompt, toPrompt } from "../shared/puzzle";

export interface DailyPuzzles {
  readonly day: number;
  /** One puzzle per tier: within reach, worth working at, and a wall. */
  readonly puzzles: Readonly<Record<DailyTier, Puzzle>>;
  readonly resetsAt: number;
}

const BOARD_ROW = new RegExp(`^[IJLOSTZG.]{${BOARD_WIDTH}}$`);
const PIECE_LETTERS = new Set(["I", "J", "L", "O", "S", "T", "Z"]);

function assertValid(puzzle: unknown, index: number): Puzzle {
  const candidate = puzzle as Puzzle;
  const problem = (detail: string) => new Error(`puzzles.json entry ${index}: ${detail}`);

  if (!Number.isInteger(candidate?.id)) throw problem("missing numeric id");
  if (!Array.isArray(candidate.queue) || candidate.queue.length === 0) {
    throw problem("empty queue");
  }
  if (!Array.isArray(candidate.board)) throw problem("missing board");
  for (const row of candidate.board) {
    // The alphabet matters as much as the width: `decodeRow` casts whatever it
    // finds, so a stray character would reach the engine as an undefined mino.
    if (typeof row !== "string" || !BOARD_ROW.test(row)) {
      throw problem(`board row must be ${BOARD_WIDTH} of [IJLOSTZG.], got ${JSON.stringify(row)}`);
    }
  }
  for (const piece of candidate.queue) {
    if (!PIECE_LETTERS.has(piece)) throw problem(`queue holds ${JSON.stringify(piece)}`);
  }
  if (candidate.hold !== null && !PIECE_LETTERS.has(candidate.hold)) {
    throw problem(`hold is ${JSON.stringify(candidate.hold)}`);
  }
  if (!(candidate.targetAttack > 0)) throw problem("target attack must be positive");
  if (!Array.isArray(candidate.solution) || candidate.solution.length === 0) {
    throw problem("missing solution");
  }
  return candidate;
}

export class PuzzleArchive {
  private readonly byId: ReadonlyMap<number, Puzzle>;
  private readonly tiers: Readonly<Record<DailyTier, readonly Puzzle[]>>;

  private constructor(
    readonly puzzles: readonly Puzzle[],
    private readonly dayOptions: DayOptions,
  ) {
    this.byId = new Map(puzzles.map((puzzle) => [puzzle.id, puzzle]));
    // Partitioned once, and sorted by id inside each tier. The rotation is an
    // index into these arrays, so an order that depended on how the file
    // happened to be written would deal different puzzles after a rebuild.
    const tiers = byTier([...puzzles].sort((a, b) => a.id - b.id));
    this.tiers = tiers;
    for (const tier of DAILY_TIERS) {
      if (tiers[tier].length === 0) {
        throw new Error(`The archive has no ${tier} puzzles; a day needs one of each`);
      }
    }
  }

  /** Each tier walks its own rotation; the stream keeps them from marching together. */
  private static readonly STREAM: Readonly<Record<DailyTier, number>> = {
    easy: 1,
    medium: 2,
    hard: 3,
  };

  static load(path: string, dayOptions: DayOptions = {}): PuzzleArchive {
    let parsed: { puzzles?: unknown[] };
    try {
      parsed = JSON.parse(readFileSync(path, "utf8"));
    } catch (error) {
      throw new Error(
        `Could not read ${path}. Run \`bun run puzzles\` to generate it. (${String(error)})`,
        { cause: error },
      );
    }
    const list = parsed.puzzles;
    if (!Array.isArray(list) || list.length === 0) {
      throw new Error(`${path} contains no puzzles`);
    }
    return new PuzzleArchive(list.map(assertValid), dayOptions);
  }

  get(id: number): Puzzle | undefined {
    return this.byId.get(id);
  }

  /** One tier's puzzle for a day. */
  forTier(day: number, tier: DailyTier): Puzzle {
    const pool = this.tiers[tier];
    return pool[puzzleIndexForDay(day, pool.length, PuzzleArchive.STREAM[tier])]!;
  }

  /**
   * The three puzzles for a given day number, defaulting to today.
   *
   * Memoised on the day. Everything in here is constant for a calendar day and
   * four routes ask for it per request; the cost is dominated by `nextResetAt`,
   * which formats a wall clock three times through Intl.
   */
  private cached: DailyPuzzles | null = null;

  forDay(day: number = dayNumber(Date.now(), this.dayOptions)): DailyPuzzles {
    if (this.cached?.day === day) return this.cached;
    this.cached = {
      day,
      puzzles: {
        easy: this.forTier(day, "easy"),
        medium: this.forTier(day, "medium"),
        hard: this.forTier(day, "hard"),
      },
      resetsAt: nextResetAt(Date.now(), this.dayOptions),
    };
    return this.cached;
  }

  today(): DailyPuzzles {
    return this.forDay();
  }

  /** Which of a day's three a puzzle is, or null if it is not one of them. */
  tierOfDay(day: number, puzzleId: number): DailyTier | null {
    return DAILY_TIERS.find((tier) => this.forTier(day, tier).id === puzzleId) ?? null;
  }

  currentDay(): number {
    return dayNumber(Date.now(), this.dayOptions);
  }

  prompt(puzzle: Puzzle): PuzzlePrompt {
    return toPrompt(puzzle);
  }
}
