/**
 * The puzzle archive, loaded once and served from memory.
 *
 * `data/puzzles.json` is generated by `tools/build-puzzles.ts`; this module is
 * the only thing that reads it, and it validates on load so a bad build fails
 * at startup instead of halfway through someone's run.
 *
 * Since accepted player submissions joined it there are two sources, and they
 * meet in {@link PuzzleArchive.load}. The second one is passed in rather than
 * read here: those rows live in SQLite, and an archive that had to open a
 * database to load itself could not be tested — nor built — without one, which
 * is the same argument `PastDays` makes from the other side of the same seam.
 *
 * Officers' corrections arrive by the same door, for the same reason, and go on
 * last — see {@link applyOverrides}.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  byTier,
  DAILY_TIERS,
  type DailyTier,
  type DayOptions,
  dayNumber,
  nextResetAt,
  puzzleIndexForDay,
} from "../shared/daily";
import {
  BOARD_WIDTH,
  type ClearRequirement,
  clearShortfall,
  COMMUNITY_ID_BASE,
  type Puzzle,
  type PuzzlePrompt,
  type SolutionStep,
  toPrompt,
} from "../shared/puzzle";
// Type-only, and it has to stay that way: `server/puzzle-overrides.ts` imports
// `bun:sqlite`, and the point of this file's header is that loading an archive
// needs no database. A type erases; an import would not.
import type { OverrideFields, PuzzleOverride } from "./puzzle-overrides";

/**
 * Folds `data/solutions.json` back in, when it is there.
 *
 * The answers are not in the tracked archive — a solution beside its puzzle in
 * a public repository is a published answer key — so the build writes them
 * separately and this is where the two halves meet. Absent, every puzzle still
 * loads, plays and scores; only the reveal has nothing to show, which is the
 * right way round for the thing that must not leak.
 */
function withSolutions(puzzles: Puzzle[], archivePath: string): Puzzle[] {
  const beside = join(dirname(archivePath), "solutions.json");
  if (!existsSync(beside)) return puzzles;

  // A corrupt file costs exactly what a missing one costs, and no more.
  //
  // This runs at module scope, so an unguarded `JSON.parse` here is the whole
  // server refusing to boot for every player — over the one file the docblock
  // above says everything works without. A `bun run puzzles` interrupted
  // mid-write leaves a file that passes `existsSync` and throws on parse, and
  // `{"solutions": null}` throws on `.map` a line later.
  let listed: unknown;
  try {
    listed = (JSON.parse(readFileSync(beside, "utf8")) as { solutions?: unknown }).solutions;
  } catch (error) {
    console.warn(`[puzzle] ${beside} is not valid JSON; serving without solutions.`, error);
    return puzzles;
  }
  if (!Array.isArray(listed)) {
    console.warn(`[puzzle] ${beside} has no solutions array; serving without solutions.`);
    return puzzles;
  }

  const book = new Map<number, Pick<Puzzle, "solution" | "source">>(
    (listed as Puzzle[]).map((entry) => [
      entry.id,
      { solution: entry.solution, source: entry.source },
    ]),
  );
  return puzzles.map((puzzle) => ({ ...puzzle, ...book.get(puzzle.id) }));
}

/**
 * What a recorded answer was played against.
 *
 * Two copies of the same puzzle set drift: `data/puzzles.json` is rebuilt from
 * the club's CSV exports, the archive is synced from the live sheet, and today
 * three of 138 disagree — id 8 is "fourtris mogs" in one and "misplaced heart"
 * in the other. So an answer is matched to a puzzle by the *shape it was played
 * against*, never by id. An id join would put another puzzle's answer behind
 * this one's reveal, which is the join already removed from
 * `tools/audit-archive.ts` for the same reason.
 *
 * Title, author, goal and difficulty are deliberately absent: an officer may
 * correct any of them, and none changes whether a recorded line still lands.
 */
export function shapeKey(
  puzzle: Pick<Puzzle, "board" | "queue" | "hold" | "targetAttack">,
): string {
  return JSON.stringify([puzzle.board, puzzle.queue, puzzle.hold ?? null, puzzle.targetAttack]);
}

/**
 * Fills in answers for puzzles this box has none for.
 *
 * `data/solutions.json` is untracked — an answer key beside the puzzles is an
 * answer key for everybody — so on an ordinary deploy every club puzzle arrives
 * answerless and the reveal has nothing to show. The answers are not missing
 * from the box, though: they are committed inside `data/archive/puzzles.sqlite`,
 * which every checkout has. This is the wiring that was never there.
 *
 * Additive only. A puzzle that already has an answer keeps it: `solutions.json`
 * is the source the rest of that box's build was derived from, so where the two
 * disagree the local one is the one to trust.
 */
export function withFallbackSolutions(
  puzzles: readonly Puzzle[],
  answers: ReadonlyMap<string, readonly SolutionStep[]>,
): Puzzle[] {
  if (answers.size === 0) return [...puzzles];
  return puzzles.map((puzzle) => {
    if (puzzle.solution?.length) return puzzle;
    const answer = answers.get(shapeKey(puzzle));
    return answer ? { ...puzzle, solution: answer } : puzzle;
  });
}

export interface DailyPuzzles {
  readonly day: number;
  /** One puzzle per tier: within reach, worth working at, and a wall. */
  readonly puzzles: Readonly<Record<DailyTier, Puzzle>>;
  readonly resetsAt: number;
}

const BOARD_ROW = new RegExp(`^[IJLOSTZG.]{${BOARD_WIDTH}}$`);
const PIECE_LETTERS = new Set(["I", "J", "L", "O", "S", "T", "Z"]);

/** Everything about a puzzle the engine has to be able to read. */
export type BoardShape = Pick<Puzzle, "board" | "queue" | "hold">;

/**
 * What is wrong with a board, queue and hold — or null when nothing is.
 *
 * Split out of {@link assertValid} so that the file the build writes and the
 * puzzles players submit are held to one rule rather than two that drift.
 * Everything else `assertValid` checks belongs to the archive alone: a
 * submission has no id and no target yet, because both are the server's to
 * assign and neither is the author's to claim.
 *
 * It reports the fault instead of throwing it so each caller can say it in its
 * own voice — "puzzles.json entry 12" to an operator watching a startup fail,
 * a plain sentence to a player about to lose the puzzle they just wrote.
 */
export function boardProblem(candidate: BoardShape): string | null {
  if (!Array.isArray(candidate.queue) || candidate.queue.length === 0) return "empty queue";
  if (!Array.isArray(candidate.board)) return "missing board";
  for (const row of candidate.board) {
    // The alphabet matters as much as the width: `decodeRow` casts whatever it
    // finds, so a stray character would reach the engine as an undefined mino.
    if (typeof row !== "string" || !BOARD_ROW.test(row)) {
      return `board row must be ${BOARD_WIDTH} of [IJLOSTZG.], got ${JSON.stringify(row)}`;
    }
  }
  for (const piece of candidate.queue) {
    if (!PIECE_LETTERS.has(piece)) return `queue holds ${JSON.stringify(piece)}`;
  }
  // A missing hold is a fault, not an empty one. `null` is how "nothing in
  // hold" is spelt everywhere else, and a body that simply left the field out
  // would otherwise reach the engine as undefined.
  if (candidate.hold !== null && !PIECE_LETTERS.has(candidate.hold)) {
    return `hold is ${JSON.stringify(candidate.hold)}`;
  }
  return null;
}

/**
 * One puzzle, held to the archive's rule, whichever source it came from.
 *
 * `named` rather than an index because there are two sources now and a message
 * reading "entry 4" would send an operator to the wrong one. The rule itself is
 * deliberately identical for both: an accepted submission was checked on the
 * way into the database and again at accept, so a row that fails here is a
 * database somebody edited, and the archive's own stance on that — say so at
 * startup rather than halfway through a run — is the one this file was written
 * around. Skipping the bad row instead would be quieter and worse: a day
 * already pinned to it would throw in `DaySchedule.resolve` about a puzzle
 * nothing would name, and `/api/archive/:id` would answer 404 for a puzzle
 * players hold runs against.
 */
function assertValid(puzzle: unknown, named: string): Puzzle {
  const candidate = puzzle as Puzzle;
  const problem = (detail: string) => new Error(`${named}: ${detail}`);

  if (!Number.isInteger(candidate?.id)) throw problem("missing numeric id");
  const fault = boardProblem(candidate);
  if (fault) throw problem(fault);
  if (!(candidate.targetAttack > 0)) throw problem("target attack must be positive");
  // No solution check. They live in data/solutions.json, which is untracked, so
  // a checkout without it is the ordinary case rather than a broken build.
  return candidate;
}

/**
 * What is wrong with a stored correction — or null when nothing is.
 *
 * Reports the fault instead of throwing it, the way {@link boardProblem} does
 * and for the same reason: the two callers say it in different voices. The
 * merge below logs it and serves the source; the review page shows the officer
 * the same effective values the next boot will.
 *
 * Deliberately narrower than the rule the PATCH route holds a *request* to.
 * That one is where lengths and the difficulty scale are enforced, because a
 * bad correction has to be a 400 to the officer who typed it rather than a row
 * anything downstream has to cope with. This is the check on a row nobody typed
 * — SQLite's column types are advisory, so a hand-edited `difficulty` can be
 * the string "very hard" — and it stops at "is this the kind of value the code
 * can act on", which is exactly where `jsonList` and `Store.pinnedRushPool`
 * stop for their own columns. A full second copy of the route's rules here
 * would be a second rule to keep in step, and the one that fired at boot would
 * be the one nobody could answer.
 */
export function overrideProblem(override: OverrideFields): string | null {
  for (const [field, value] of [
    ["title", override.title],
    ["author", override.author],
    ["goal", override.goal],
    ["set", override.set],
  ] as const) {
    if (value !== null && (typeof value !== "string" || value.length === 0)) {
      return `${field} is ${JSON.stringify(value)}`;
    }
  }
  // Finite, not merely a number: `dailyTierOf` and `rushBand` both compare it,
  // and a NaN loses every comparison it is in — so an unrated-looking puzzle
  // would appear in the hard tier by falling through rather than by matching.
  if (override.difficulty !== null && !Number.isFinite(override.difficulty)) {
    return `difficulty is ${JSON.stringify(override.difficulty)}`;
  }
  return null;
}

/**
 * One puzzle with one officer's correction laid over it.
 *
 * `??` per field, which is what "NULL means use the source" reads as. Total and
 * unchecked on purpose: {@link overrideProblem} is the gate, and both callers
 * run it first, so a check in here would be a third place holding the same
 * opinion.
 *
 * Nothing that identifies the puzzle or decides what a solve was worth can be
 * reached from here — see `OVERRIDABLE_FIELDS` for why that is the whole point.
 */
export function withOverride(puzzle: Puzzle, override: OverrideFields): Puzzle {
  const goal = override.goal ?? puzzle.goal;
  return {
    ...puzzle,
    title: override.title ?? puzzle.title,
    author: override.author ?? puzzle.author,
    goal,
    difficulty: override.difficulty ?? puzzle.difficulty,
    set: override.set ?? puzzle.set,
    // `requiredClears` rides the spread untouched, and that is the whole rule:
    // the requirement is read off the puzzle's own replayed answer, so a fix to
    // the *wording* cannot move it. This used to re-derive from the corrected
    // sentence, which was the right instinct under a scheme where the sentence
    // was the source. It is not any more — an officer rewriting a goal is
    // describing the puzzle, not re-scoping it, and `targetAttack` is kept out
    // of OVERRIDABLE_FIELDS for exactly the same reason.
  };
}

/**
 * The last gate: no puzzle demands a clear its own answer never makes.
 *
 * Under the current scheme the requirement is *derived* from the answer, so at
 * the moment it is written the two cannot disagree. This is what keeps that true
 * afterwards. A creator may edit a published puzzle — `archive-rows.ts` has a
 * content log and a discovery void for exactly that — and an edit that changes
 * the answer leaves a requirement derived from a solve nobody can reproduce any
 * more. A hand-fixed sqlite row and a backup restored from before a re-solve
 * land in the same state.
 *
 * A disarmed puzzle is still scored on **attack**. `targetAttack` is derived
 * from the answer and is the bar runs are actually filed against; a puzzle that
 * is wrong about its clears is not thereby wrong about its damage. The player
 * gets a puzzle that is merely easier than its prose claims, which is the
 * failure worth having — the alternative is a puzzle nobody can solve.
 *
 * No answer key on the box means no judgement, not a failed one:
 * `solutions.json` is untracked, so on an ordinary deploy this runs blind and
 * must leave the requirement alone. Silently — a warning per puzzle per boot, on
 * every box with no answer key, is a log nobody reads twice.
 */
export function withoutUnmeetableClears(puzzles: readonly Puzzle[]): Puzzle[] {
  return puzzles.map((puzzle) => {
    const required = puzzle.requiredClears ?? [];
    const answer = puzzle.solution;
    if (required.length === 0 || !answer) return puzzle;

    const short = clearShortfall(
      answer.flatMap((step) => (step.clear ? [step.clear] : [])),
      required,
    );
    if (short.length === 0) return puzzle;

    console.warn(
      `[puzzle] ${puzzle.id} requires clears its own answer does not make ` +
        `(short ${short.map((entry) => `${entry.count} ${entry.clear}`).join(", ")}); ` +
        `serving it on attack alone. Its goal is "${puzzle.goal}" — fix the wording, ` +
        "the answer, or the requirement.",
    );
    return { ...puzzle, requiredClears: [] };
  });
}

/**
 * The corrections, over the club's file and the accepted submissions alike.
 *
 * One pass over the merged list, which is the point: a correction is written
 * one way whatever a puzzle's source was, so there is one place that reads it
 * back. Corrections go on **last** — after both sources are in and after each
 * entry has been held to {@link assertValid} — so what an officer sees is what
 * the archive serves, with nothing downstream of it to disagree.
 *
 * Then two lines of defence, and they are here because the failure mode is not
 * a wrong title. `PuzzleArchive.load` runs at module scope and throws, so a
 * correction that made a puzzle invalid would stop the whole server booting for
 * every player — over one officer's typo, with the only way back being an edit
 * to the database by hand. This codebase has been bitten by that shape once
 * already: see the `targetAttack > 0` check in `server/review-routes.ts`.
 *
 * So a suspect correction is dropped and the source is served, loudly. The
 * whole row goes rather than the offending field, because a half-applied
 * correction is a puzzle in a state nobody ever wrote — source or override are
 * the only two things a reader should have to reason about.
 *
 * The re-run of `assertValid` at the end costs a walk of a list already in
 * memory and buys the guarantee structurally: none of the five editable fields
 * is one of the three things it checks, so an override *cannot* make a puzzle
 * invalid today — and this is what keeps that true if the editable set ever
 * grows, rather than a comment asking the next person to notice.
 */
function applyOverrides(
  puzzles: readonly Puzzle[],
  overrides: readonly PuzzleOverride[],
): Puzzle[] {
  if (overrides.length === 0) return [...puzzles];
  const corrections = new Map(overrides.map((override) => [override.puzzleId, override]));
  return puzzles.map((puzzle) => {
    const correction = corrections.get(puzzle.id);
    if (!correction) return puzzle;

    const refuse = (detail: string): Puzzle => {
      console.warn(
        `[puzzle] ignoring the correction to puzzle ${puzzle.id} (${detail}); serving what ` +
          "its source says. Revert it with DELETE /api/review/puzzles/" +
          `${puzzle.id}/override, or fix the row in puzzle_overrides.`,
      );
      return puzzle;
    };

    const fault = overrideProblem(correction);
    if (fault) return refuse(fault);
    const corrected = withOverride(puzzle, correction);
    try {
      return assertValid(corrected, `puzzle ${puzzle.id} as corrected`);
    } catch (error) {
      return refuse(String(error));
    }
  });
}

/**
 * The corrected archive, unless correcting it would leave a tier empty.
 *
 * `applyOverrides` already refuses a correction that makes one puzzle invalid,
 * so "an override cannot break a puzzle" is structural. A tier is the same
 * promise one level up, and it was guarded nowhere: difficulty is what `byTier`
 * partitions on and what a reviewer may now edit, so moving the last easy
 * puzzle out of its band threw in the constructor — at module scope, before any
 * route exists. The server would not boot, and the DELETE that undoes the
 * correction lives on that server, so the documented way back was unreachable
 * from anywhere but sqlite3.
 *
 * Falling back to the sources whole rather than to the offending row: the empty
 * band is a property of the set, and picking which correction caused it is a
 * guess where serving what the club wrote is not. Every correction is still on
 * file and the officer's next DELETE lands on a server that is running.
 */
function correctedOrSource(
  sources: readonly Puzzle[],
  overrides: readonly PuzzleOverride[],
): { puzzles: Puzzle[]; applied: boolean } {
  const corrected = applyOverrides(sources, overrides);
  const missing = DAILY_TIERS.filter((tier) => byTier(corrected)[tier].length === 0);
  if (missing.length === 0) return { puzzles: corrected, applied: true };
  console.warn(
    `[puzzle] ignoring every correction: they leave no ${missing.join(" or ")} puzzle, ` +
      "and a day needs one of each. Revert one through the review tool and restart.",
  );
  // `applied` travels with the puzzles because the review tool has to say so.
  // A console warning on the VPS is invisible to the officer holding the link,
  // and the tool was reporting every correction as in force while players were
  // being served the sources — promising something the server will not do.
  return { puzzles: [...sources], applied: false };
}

/**
 * A published row, if it is one the engine can play — or nothing, loudly.
 *
 * The opposite of {@link assertValid}'s stance, and on purpose. The file and
 * an accepted submission are both checked by a person before they reach here,
 * so a bad one is worth refusing to boot over. A published row is not: Discord's
 * `/archive sync` publishes whatever the sheet held, with nobody reading it in
 * between, so one malformed row would otherwise take the server down at its
 * next start — for every player, with no route left to undo it from. The
 * sync's own replay makes that unlikely; this makes it survivable. Skipping
 * the row falls back to the file's entry for that id, where there is one.
 */
function servable(puzzle: Puzzle): Puzzle[] {
  try {
    return [assertValid(puzzle, `published puzzle ${puzzle?.id}`)];
  } catch (error) {
    console.warn(`[puzzle] not serving ${String(error).replace(/^Error: /, "")}.`);
    return [];
  }
}

/**
 * The published archive laid over the club's file.
 *
 * A published row replaces the file's entry for its id, and a row the file has
 * never heard of is added after it. The file stays the seed rather than being
 * retired: every box has it, while `archive_puzzles` is empty until somebody
 * syncs, and a server that could only play what had been synced would boot to
 * nothing on a fresh checkout.
 *
 * Additions go after the file's entries rather than being sorted in. The daily
 * rotation re-sorts every tier by id in the constructor, so the order here only
 * reaches a rush pool pinned for a day nobody has asked for yet.
 */
export function withPublished(file: readonly Puzzle[], published: readonly Puzzle[]): Puzzle[] {
  if (published.length === 0) return [...file];
  const replacing = new Map(published.map((puzzle) => [puzzle.id, puzzle]));
  const known = new Set(file.map((puzzle) => puzzle.id));
  return [
    ...file.map((puzzle) => replacing.get(puzzle.id) ?? puzzle),
    ...published.filter((puzzle) => !known.has(puzzle.id)),
  ];
}

/**
 * Everything a run on a puzzle is scored against.
 *
 * A board, queue, hold or target that moves under a player mid-solve scores
 * their keystrokes against a puzzle they were never shown; so does a clear
 * requirement, now that it is enforced. Metadata is deliberately absent.
 */
function playKey(puzzle: Puzzle): string {
  return JSON.stringify([shapeKey(puzzle), puzzle.requiredClears ?? []]);
}

/** What {@link PuzzleArchive.reconcile} did, for the log and the bot's reply. */
export interface ArchiveChange {
  /** New to this process, and playable from now on. */
  readonly added: readonly number[];
  /**
   * Whose board, queue, hold, target or requirement changed on file. Still
   * served as they were — somebody may be halfway through one — until the
   * server next starts.
   */
  readonly held: readonly number[];
  /** Served before and missing from the new sources. Still served; see `reconcile`. */
  readonly kept: readonly number[];
}

export class PuzzleArchive {
  // Not `readonly`: `adopt` replaces all of them at once, in place, so that the
  // one object every route and the schedule already hold serves the new pool.
  private byId: ReadonlyMap<number, Puzzle>;
  private originalById: ReadonlyMap<number, Puzzle>;
  private tiers: Readonly<Record<DailyTier, readonly Puzzle[]>>;

  /**
   * @param puzzles what everything plays, reads and lists: sources with every
   *   officer's correction already on them.
   * @param originals the same puzzles as their sources have them, kept only so
   *   the review tool can show what a correction changed *from*. Nothing else
   *   should read these — a rotation, a listing or a prompt built from them
   *   would be serving a correction that has already been made.
   */
  private constructor(
    public puzzles: readonly Puzzle[],
    public originals: readonly Puzzle[],
    private readonly dayOptions: DayOptions,
    /**
     * Whether the corrections on file are the ones being served.
     *
     * False when `correctedOrSource` shelved the lot — a corrected set that
     * empties a daily band is refused whole. Read by the review tool, which
     * would otherwise show an officer their correction applied while every
     * player got the source.
     */
    public correctionsApplied: boolean = true,
  ) {
    this.byId = new Map(puzzles.map((puzzle) => [puzzle.id, puzzle]));
    this.originalById = new Map(originals.map((puzzle) => [puzzle.id, puzzle]));
    // The Map is exactly why this check has to exist. It resolves a duplicate
    // id cleanly — last one wins — while both copies stay in `puzzles`, which
    // is the array the daily rotation indexes into and the rush pool is
    // filtered out of, so the same puzzle would be dealt twice under one name
    // and `runs.puzzle_id`, which has no foreign key, would merge two puzzles'
    // history with nothing anywhere to complain. Two allocators write into this
    // array now — the club's sheet and `nextCommunityPuzzleId` — and this is
    // the one place they are ever in the same list.
    if (this.byId.size !== puzzles.length) {
      // Only ever walked on the way to throwing, so the quadratic scan costs
      // nothing and reads as what it is.
      const clash = puzzles.find(
        (puzzle, index) => puzzles.findIndex((other) => other.id === puzzle.id) !== index,
      );
      throw new Error(
        `Two puzzles claim id ${clash?.id}. Club ids and the community band ` +
          `(${COMMUNITY_ID_BASE}+) must never meet; renumbering the sheet into the ` +
          "band is the way this happens.",
      );
    }
    // Partitioned once, and sorted by id inside each tier. The rotation is an
    // index into these arrays, so an order that depended on how the file
    // happened to be written would deal different puzzles after a rebuild.
    const tiers = byTier([...puzzles].sort((a, b) => a.id - b.id));
    this.tiers = tiers;
    for (const tier of DAILY_TIERS) {
      if (tiers[tier].length === 0) {
        throw new Error(`The archive has no ${tier} puzzles; a day needs one of each`);
      }
    }
  }

  /** Each tier walks its own rotation; the stream keeps them from marching together. */
  private static readonly STREAM: Readonly<Record<DailyTier, number>> = {
    easy: 1,
    medium: 2,
    hard: 3,
    // A stream of its own, so extreme walks its own rotation rather than
    // shadowing hard's — the two are dealt on the same day and a shared stream
    // would pair the same two puzzles together every cycle.
    extreme: 4,
  };

  /**
   * The club's file plus whatever officers have accepted, as one archive.
   *
   * `community` is a third argument rather than something read in here for the
   * reason the file header gives, and it comes last so that neither of the two
   * existing call shapes had to move. The accepted puzzles carry their own
   * solutions, so {@link withSolutions} is the file's business alone — there is
   * no `data/solutions.json` entry to write for a puzzle that was never built.
   *
   * They go in *after* the file, which settles nothing about the rotation —
   * every tier is re-sorted by id in the constructor and the rush pool is
   * pinned per day — and everything about which of two puzzles sharing an id
   * the duplicate check names first.
   *
   * `overrides` comes last and is laid on last, over both. It is a fourth
   * argument for the same reason `community` was a third: those rows live in
   * SQLite and this file must go on loading without one.
   */
  /**
   * @param answers answers for puzzles this box has none of its own for, keyed
   * by {@link shapeKey}. Passed in rather than read here: loading an archive
   * needs no database, and this file's header keeps it that way — the reader
   * lives in `server/archive-solutions.ts`.
   * @param published the rows `archive_puzzles` has published, laid over the
   * file by {@link withPublished}. Passed in for the same reason as the rest.
   */
  static load(
    path: string,
    dayOptions: DayOptions = {},
    community: readonly Puzzle[] = [],
    overrides: readonly PuzzleOverride[] = [],
    answers: ReadonlyMap<string, readonly SolutionStep[]> = new Map(),
    published: readonly Puzzle[] = [],
  ): PuzzleArchive {
    let parsed: { puzzles?: unknown[] };
    try {
      parsed = JSON.parse(readFileSync(path, "utf8"));
    } catch (error) {
      throw new Error(
        `Could not read ${path}. Run \`bun run puzzles\` to generate it. (${String(error)})`,
        { cause: error },
      );
    }
    const list = parsed.puzzles;
    if (!Array.isArray(list) || list.length === 0) {
      throw new Error(`${path} contains no puzzles`);
    }
    const file = withPublished(
      withSolutions(
        list.map((entry, index) => assertValid(entry, `puzzles.json entry ${index}`)),
        path,
      ),
      published.flatMap((puzzle) => servable(puzzle)),
    );
    const accepted = community.map((puzzle) =>
      assertValid(puzzle, `accepted puzzle ${puzzle?.id}`),
    );
    // Answers from the tracked archive for anything the two sources above left
    // without one. Additive and shape-matched; see `withFallbackSolutions`.
    const sources = withFallbackSolutions([...file, ...accepted], answers);
    const { puzzles, applied } = correctedOrSource(sources, overrides);
    // Last, over the corrected list: a correction can re-derive a requirement,
    // so this has to see what will actually be served. `sources` is left as its
    // author wrote it — the review tool's job is to say what the source says.
    return new PuzzleArchive(withoutUnmeetableClears(puzzles), sources, dayOptions, applied);
  }

  /**
   * A freshly loaded archive, made safe to serve in place of a running one.
   *
   * People are mid-solve on the running one, and nothing records the board a
   * run was played on — every route verifies a submission against whatever the
   * archive holds for that id *when it arrives*. So three rules, and none of
   * them is about the rotation, which `DaySchedule` pins separately:
   *
   * - **A new id is served at once.** Nobody can be holding a puzzle that did
   *   not exist.
   * - **A changed board is not.** If what a run is scored against moved —
   *   see {@link playKey} — the puzzle is served exactly as it was, title and
   *   all, until the server next starts. Swapping it would score a player's
   *   keystrokes against a board they were never shown; and serving the new
   *   title or goal over the old board would describe a puzzle that is not
   *   there. Metadata on an unchanged board goes live.
   * - **Nothing is dropped.** A day already pinned to a missing id throws in
   *   `DaySchedule.resolve`, and a player holding it would get a 404. The
   *   sources only ever grow today, so this is a guard rather than a feature.
   *
   * Built through the constructor, so the duplicate-id and empty-tier checks
   * run on the merged pool and a bad one throws here — before anything has
   * been swapped.
   */
  static reconcile(
    current: PuzzleArchive,
    next: PuzzleArchive,
  ): { archive: PuzzleArchive; change: ArchiveChange } {
    const added: number[] = [];
    const held: number[] = [];
    const puzzles = next.puzzles.map((incoming) => {
      const serving = current.get(incoming.id);
      if (!serving) {
        added.push(incoming.id);
        return incoming;
      }
      if (playKey(serving) === playKey(incoming)) return incoming;
      held.push(incoming.id);
      return serving;
    });
    const present = new Set(next.puzzles.map((puzzle) => puzzle.id));
    const kept = current.puzzles.filter((puzzle) => !present.has(puzzle.id));
    const originals = [
      ...next.originals,
      ...kept.flatMap((puzzle) => current.original(puzzle.id) ?? []),
    ];
    return {
      archive: new PuzzleArchive(
        [...puzzles, ...kept],
        originals,
        current.dayOptions,
        next.correctionsApplied,
      ),
      change: { added, held, kept: kept.map((puzzle) => puzzle.id) },
    };
  }

  /**
   * Becomes `next`, in place.
   *
   * In place because everything that serves a puzzle already holds this
   * object: the routes, `DaySchedule`, the review tool. Replacing the binding
   * instead would leave each of them on the old pool. JavaScript runs one
   * request handler at a time, so there is no moment where half of this is
   * visible.
   */
  adopt(next: PuzzleArchive): void {
    this.puzzles = next.puzzles;
    this.originals = next.originals;
    this.correctionsApplied = next.correctionsApplied;
    this.byId = next.byId;
    this.originalById = next.originalById;
    this.tiers = next.tiers;
    this.cached = null;
  }

  get(id: number): Puzzle | undefined {
    return this.byId.get(id);
  }

  /**
   * Every puzzle this archive serves, corrections already applied.
   *
   * For callers that need the whole pool rather than one puzzle — seeding the
   * reference solutions at boot is the first. Deliberately the *corrected* list
   * and not `sources`: what is on record should be what players are actually
   * served.
   */
  get all(): readonly Puzzle[] {
    return [...this.byId.values()];
  }

  /**
   * One puzzle as its source has it, before any officer's correction.
   *
   * For the review tool and nothing else, which is why it sits beside
   * {@link get} rather than replacing it anywhere: every other reader wants the
   * corrected puzzle, and this one only wants to say what changed.
   */
  original(id: number): Puzzle | undefined {
    return this.originalById.get(id);
  }

  /** One tier's puzzle for a day. */
  forTier(day: number, tier: DailyTier): Puzzle {
    const pool = this.tiers[tier];
    return pool[puzzleIndexForDay(day, pool.length, PuzzleArchive.STREAM[tier])]!;
  }

  /**
   * The puzzles for a given day number, defaulting to today.
   *
   * Memoised on the day. Everything in here is constant for a calendar day and
   * four routes ask for it per request; the cost is dominated by `nextResetAt`,
   * which formats a wall clock three times through Intl.
   */
  private cached: DailyPuzzles | null = null;

  forDay(day: number = dayNumber(Date.now(), this.dayOptions)): DailyPuzzles {
    if (this.cached?.day === day) return this.cached;
    this.cached = {
      day,
      puzzles: {
        easy: this.forTier(day, "easy"),
        medium: this.forTier(day, "medium"),
        hard: this.forTier(day, "hard"),
        extreme: this.forTier(day, "extreme"),
      },
      resetsAt: nextResetAt(Date.now(), this.dayOptions),
    };
    return this.cached;
  }

  today(): DailyPuzzles {
    return this.forDay();
  }

  /** Which of a day's tiers a puzzle is, or null if it is not one of them. */
  tierOfDay(day: number, puzzleId: number): DailyTier | null {
    return DAILY_TIERS.find((tier) => this.forTier(day, tier).id === puzzleId) ?? null;
  }

  currentDay(): number {
    return dayNumber(Date.now(), this.dayOptions);
  }

  /**
   * When the puzzle turns over. Here beside {@link currentDay} for the same
   * reason: the club's zone was configured once, into this object, and a caller
   * that had to be handed it again to answer the other half of "what day is it"
   * is a second place for the zone to be wrong.
   */
  resetsAt(): number {
    return nextResetAt(Date.now(), this.dayOptions);
  }

  /**
   * A puzzle as a player receives it — with the clear requirement only when the
   * server is actually going to enforce it.
   *
   * The flag has to reach the client, and this is how it does. `PuzzleRun` ends
   * an attempt on `solvesPuzzle`, which reads `requiredClears` off the prompt;
   * gating only the server left the client enforcing a rule the server had been
   * told not to apply. In rush that is visible: a skipped or buzzer-ended
   * segment pushes a live log, so a run the player watched go unsolved came
   * back counted as solved, and the ranked score exceeded what the HUD showed.
   *
   * Withholding the field rather than shipping the mode keeps one rule in one
   * place. A client that cannot see a requirement cannot enforce one, so `log`
   * and `off` put both halves back exactly where `origin/main` had them, and
   * the promise this rollout is built on — that forgetting to turn enforcement
   * on costs nothing but a quiet log — is true rather than nearly true.
   *
   * **`enforce` is an argument, not a config read, and defaults to false.**
   * Reading `config` here would put it in this module's import graph, and eight
   * test files import `PuzzleArchive` at module scope *before* their `beforeAll`
   * sets `DATABASE_PATH` — so config would settle on the wrong database and the
   * suite would share one store across files that each asked for their own.
   * That is the hazard `tests/duel.ts` and `tests/submissions.test.ts` both have
   * headers about, and it cost five failures when this was written the other
   * way. The default is the withholding one so that a caller who forgets leaves
   * the client exactly where `origin/main` had it.
   */
  prompt(puzzle: Puzzle, enforce = false): PuzzlePrompt {
    const prompt = toPrompt(puzzle);
    if (enforce) return prompt;
    const { requiredClears: _withheld, ...loose } = prompt;
    return loose;
  }
}
